<a href="https://colab.research.google.com/github/mohak1/DDoS_Attack_Classification/blob/master/DDOS_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
 #%tensorflow_version 2.x
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Lambda, Flatten
from keras.layers import Convolution1D, Dense, Dropout, MaxPooling1D, LSTM
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from keras import callbacks
from keras.callbacks import CSVLogger
from keras.utils import to_categorical
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger
import numpy as np
np.random.seed(0)

Using TensorFlow backend.


In [0]:
#loading dataset
import pandas as pd
x = pd.read_csv("/content/drive/My Drive/dos_dataset/clean_5.csv")
y = pd.read_csv("/content/drive/My Drive/dos_dataset/y.csv")
y=y['Label']
x=x.drop(['Label'], axis=1)

#normalizing the data
normalized_df=(x-x.mean())/x.std()

In [0]:
normalized_df=normalized_df.drop(['Unnamed: 0'], axis=1)
normalized_df=normalized_df.drop(['Unnamed: 0.1'], axis=1)
normalized_df=normalized_df.drop(['Unnamed: 0.1.1'], axis=1)
normalized_df=normalized_df.drop(['Flow Bytes/s'], axis=1)
normalized_df=normalized_df.drop([' Flow Packets/s'], axis=1)


In [5]:
normalized_df.head()

Source Port   Destination IP  ...   Idle Std   Inbound
0      1.395596         0.157586  ...  -0.162793   0.19758
1      0.347887         0.157586  ...  -0.162793   0.19758
2      1.196809         0.157586  ...  -0.162793   0.19758
3      0.892029         0.157586  ...  -0.162793   0.19758
4     -0.914218         0.157586  ...  -0.162793   0.19758

[5 rows x 34 columns]

In [6]:
y.nunique()

8

In [7]:
y = pd.get_dummies(y,prefix=['Label'])
y.head()

['Label']_0  ['Label']_1  ['Label']_2  ...  ['Label']_5  ['Label']_6  ['Label']_7
0            0            0            1  ...            0            0            0
1            0            0            1  ...            0            0            0
2            0            0            1  ...            0            0            0
3            0            0            1  ...            0            0            0
4            0            0            1  ...            0            0            0

[5 rows x 8 columns]

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(normalized_df, y, test_size=0.25, random_state=0)
y_train = np.array(y_train)

In [0]:
y_train = np.array(y_train)
y_test = np.array(y_test)
X_train = np.array(X_train)
X_test = np.array(X_test)
X_train = np.reshape(X_train, (X_train.shape[0],X_train.shape[1],1))
X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1],1))

In [10]:
print('xtrain={}, ytrain={}, xtest={}, ytest={}'.format(X_train.shape,y_train.shape,X_test.shape,y_test.shape))

xtrain=(934348, 34, 1), ytrain=(934348, 8), xtest=(311450, 34, 1), ytest=(311450, 8)


In [0]:
from keras import optimizers
sgd = optimizers.SGD(lr=0.009, decay=1e-6, momentum=0.9, nesterov=True)

In [0]:
model = Sequential()
model.add(Convolution1D(64, 3, activation="relu", input_shape=(34,1)))
model.add(Convolution1D(32, 3, activation="relu"))
#model.add(MaxPooling1D(pool_size=2))
#model.add(Convolution1D(128, 3, activation="relu"))
#model.add(Convolution1D(128, 3, activation="relu"))
model.add(MaxPooling1D(pool_size=2))
#model.add(Dropout(rate=0.3))
model.add(Flatten())
#model.add(Dense(30, activation="softmax"))
#model.add(Dense(10, activation="softmax"))
model.add(Dense(8))



In [0]:
model.compile(loss="mean_absolute_error", optimizer="SGD", metrics=['accuracy'])

model.fit(X_train, y_train, epochs=20, batch_size=10, validation_data=(X_test, y_test))




Train on 934348 samples, validate on 311450 samples
Epoch 1/20





934348/934348 [==============================] - 251s 268us/step - loss: 0.0641 - acc: 0.7995 - val_loss: 0.0566 - val_acc: 0.8215
Epoch 2/20
934348/934348 [==============================] - 250s 267us/step - loss: 0.0533 - acc: 0.8234 - val_loss: 0.0513 - val_acc: 0.8190
Epoch 3/20
934348/934348 [==============================] - 250s 267us/step - loss: 0.0509 - acc: 0.8227 - val_loss: 0.0509 - val_acc: 0.8215
Epoch 4/20
934348/934348 [==============================] - 247s 264us/step - loss: 0.0496 - acc: 0.8235 - val_loss: 0.0497 - val_acc: 0.8231
Epoch 5/20
934348/934348 [==============================] - 248s 265us/step - loss: 0.0488 - acc: 0.8239 - val_loss: 0.0487 - val_acc: 0.8232
Epoch 6/20
934348/934348 [==============================] - 247s 265us/step - loss: 0.0482 - acc: 0.8244 - val_loss: 0.0476 - val_acc: 0.8232
Epoch 7/20
934348/934348 [==============================] - 249s 266us/step - loss: 0.04

KeyboardInterrupt: ignored

In [0]:
m = Sequential()
m.add(Convolution1D(128, 3, activation="relu", input_shape=(34,1)))
m.add(Convolution1D(64, 3, activation="relu"))
m.add(MaxPooling1D(pool_size=2))
#model.add(Dropout(rate=0.3))
#m.add(LSTM(500))
m.add(Flatten())
m.add(Dense(8))


m.compile(loss="mean_absolute_error", optimizer="adam", metrics=['accuracy'])
m.fit(X_train, y_train, epochs=20, batch_size=10, validation_data=(X_test, y_test))

Train on 934348 samples, validate on 311450 samples
Epoch 1/20
934348/934348 [==============================] - 430s 460us/step - loss: 0.0475 - acc: 0.8276 - val_loss: 0.0453 - val_acc: 0.8297
Epoch 2/20
934348/934348 [==============================] - 430s 460us/step - loss: 0.0443 - acc: 0.8361 - val_loss: 0.0430 - val_acc: 0.8385
Epoch 3/20
934348/934348 [==============================] - 429s 459us/step - loss: 0.0437 - acc: 0.8377 - val_loss: 0.0436 - val_acc: 0.8333
Epoch 4/20
934348/934348 [==============================] - 431s 461us/step - loss: 0.0429 - acc: 0.8391 - val_loss: 0.0424 - val_acc: 0.8393
Epoch 5/20
934348/934348 [==============================] - 429s 459us/step - loss: 0.0425 - acc: 0.8395 - val_loss: 0.0433 - val_acc: 0.8340
Epoch 6/20
934348/934348 [==============================] - 429s 459us/step - loss: 0.0423 - acc: 0.8397 - val_loss: 0.0431 - val_acc: 0.8384
Epoch 7/20
279910/934348 [=======>......................] - ETA: 4:24 - loss: 0.0424 - acc: 0.83

KeyboardInterrupt: ignored

In [0]:
m2 = Sequential()
m2.add(Convolution1D(64, 3, activation="relu", input_shape=(34,1)))
m2.add(Convolution1D(32, 3, activation="relu"))
m2.add(MaxPooling1D(pool_size=2))
m2.add(Flatten())
m2.add(Dense(8))


m2.compile(loss="mean_absolute_error", optimizer="adam", metrics=['accuracy'])
m2.fit(X_train, y_train, epochs=20, batch_size=10, validation_data=(X_test, y_test))









Train on 934348 samples, validate on 311450 samples
Epoch 1/20





934348/934348 [==============================] - 268s 287us/step - loss: 0.0472 - acc: 0.8289 - val_loss: 0.0437 - val_acc: 0.8392
Epoch 2/20
934348/934348 [==============================] - 266s 285us/step - loss: 0.0436 - acc: 0.8360 - val_loss: 0.0436 - val_acc: 0.8325
Epoch 3/20
934348/934348 [==============================] - 271s 290us/step - loss: 0.0431 - acc: 0.8367 - val_loss: 0.0468 - val_acc: 0.8170
Epoch 4/20
934348/934348 [==============================] - 275s 295us/step - loss: 0.0429 - acc: 0.8376 - val_loss: 0.0423 - val_acc: 0.8379
Epoch 5/20
934348/934348 [==============================] - 265s 284us/step - loss: 0.0425 - acc: 0.8386 - val_loss: 0.0432 - val_acc: 0.8327
Epoch 6/20
934348/934348 [==============================] - 263s 282us/step - loss: 0.0423 - acc: 0.8388 - val_loss: 0.0425 - val_acc: 0.8381
Epoch 7/20
934348/934348 [==============================] - 263s 281us/step - loss:

In [11]:
m2 = Sequential()
m2.add(Convolution1D(64, 3, activation="relu", input_shape=(34,1)))
m2.add(Convolution1D(32, 3, activation="relu"))
m2.add(MaxPooling1D(pool_size=2))
m2.add(Flatten())
m2.add(Dense(8))


m2.compile(loss="mean_absolute_error", optimizer="adam", metrics=['accuracy'])
m2.fit(X_train, y_train, epochs=20, batch_size=10, validation_data=(X_test, y_test))









Train on 934348 samples, validate on 311450 samples
Epoch 1/20





934348/934348 [==============================] - 253s 271us/step - loss: 0.0471 - acc: 0.8291 - val_loss: 0.0438 - val_acc: 0.8373
Epoch 2/20
934348/934348 [==============================] - 248s 265us/step - loss: 0.0436 - acc: 0.8357 - val_loss: 0.0438 - val_acc: 0.8374
Epoch 3/20
934348/934348 [==============================] - 247s 265us/step - loss: 0.0432 - acc: 0.8354 - val_loss: 0.0445 - val_acc: 0.8389
Epoch 4/20
934348/934348 [==============================] - 248s 266us/step - loss: 0.0430 - acc: 0.8365 - val_loss: 0.0432 - val_acc: 0.8377
Epoch 5/20
934348/934348 [==============================] - 247s 264us/step - loss: 0.0428 - acc: 0.8367 - val_loss: 0.0437 - val_acc: 0.8315
Epoch 6/20
934348/934348 [==============================] - 250s 267us/step - loss: 0.0428 - acc: 0.8369 - val_loss: 0.0432 - val_acc: 0.8378
Epoch 7/20
 19780/934348 [..............................] - ETA: 3:33 - loss: 0.042

KeyboardInterrupt: ignored

In [0]:
#save to folder
m2.save("/content/drive/My Drive/dos_dataset/final_cnn_m2.h5")

In [0]:
y_pred = m2.predict(X_test)

In [0]:
a = (y_pred > 0.5)
b = (y_test > 0.5) 

In [0]:
b=np.argmax(y_test, axis=1)

In [16]:
a=np.argmax(y_pred, axis=1)
a[2]

1

In [18]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

print('Convolution Neural Network')

print('Accuracy: %f' % (accuracy_score(a, b)*100))
print("Confusion Matrix =\n", metrics.confusion_matrix(b, a, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(b, a, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(b, a, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                 digits=2, 
                                                                 output_dict=False))

print("F1 Score = ",f1_score(a, b, average='macro'))

Convolution Neural Network
Accuracy: 83.924225
Confusion Matrix =
 [[14222    58     6    11     6    18     0     0]
 [    9 48066     2    12  1588     0    85     0]
 [   10     3 49270   530     6     3     0     0]
 [    2     0  1143 48551    29     0   550     0]
 [  163 43372     0   123  3197     0    63     0]
 [    9     0     0     2     0 49651     2     0]
 [    9     9     0  1714    10     0 48425     0]
 [   49     0     0    30     4     0   438     0]]
Recall = 0.8392422539733505


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Classification Report =
               precision    recall  f1-score   support

           0       0.98      0.99      0.99     14321
           1       0.53      0.97      0.68     49762
           2       0.98      0.99      0.98     49822
           3       0.95      0.97      0.96     50275
           4       0.66      0.07      0.12     46918
           5       1.00      1.00      1.00     49664
           6       0.98      0.97      0.97     50167
           7       0.00      0.00      0.00       521

    accuracy                           0.84    311450
   macro avg       0.76      0.74      0.71    311450
weighted avg       0.86      0.84      0.80    311450

F1 Score =  0.713088426198137
