<a href="https://colab.research.google.com/github/mohak1/DDoS_Attack_Classification/blob/master/DDOS_SGD%2C_KNN%2C_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
cd ./drive/My\ Drive/dos_dataset/

/content/drive/My Drive/dos_dataset


In [0]:
import pandas as pd
df = pd.read_csv("./clean_5.csv")
#df.info()
df=df.drop('Unnamed: 0.1',axis=1)
x=df.iloc[:,df.columns != 'Label']
y=df.iloc[:,-1]
print("x\n",x.info())
y = pd.DataFrame(y)
print('y\n',y.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1245798 entries, 0 to 1245797
Data columns (total 38 columns):
Unnamed: 0                     1245798 non-null int64
Unnamed: 0.1.1                 1245798 non-null int64
 Source Port                   1245798 non-null int64
 Destination IP                1245798 non-null int64
 Destination Port              1245798 non-null int64
 Protocol                      1245798 non-null int64
Total Length of Fwd Packets    1245798 non-null float64
 Fwd Packet Length Max         1245798 non-null float64
 Fwd Packet Length Min         1245798 non-null float64
 Fwd Packet Length Mean        1245798 non-null float64
Bwd Packet Length Max          1245798 non-null float64
 Bwd Packet Length Min         1245798 non-null float64
 Bwd Packet Length Mean        1245798 non-null float64
 Bwd Packet Length Std         1245798 non-null float64
Flow Bytes/s                   1245753 non-null float64
 Flow Packets/s                1245798 non-null float64
 Fl

In [0]:
df.describe()

Unnamed: 0  Unnamed: 0.1.1  ...       Inbound         Label
count  1.245798e+06    1.245798e+06  ...  1.245798e+06  1.245798e+06
mean   6.228985e+05    1.074318e+05  ...  9.624289e-01  3.339989e+00
std    3.596310e+05    1.089688e+05  ...  1.901566e-01  1.832971e+00
min    0.000000e+00    0.000000e+00  ...  0.000000e+00  0.000000e+00
25%    3.114492e+05    2.503600e+04  ...  1.000000e+00  2.000000e+00
50%    6.228985e+05    7.408800e+04  ...  1.000000e+00  3.000000e+00
75%    9.343478e+05    1.462510e+05  ...  1.000000e+00  5.000000e+00
max    1.245797e+06    6.652080e+05  ...  1.000000e+00  7.000000e+00

[8 rows x 39 columns]

In [0]:
#normalizating the data
#df.iloc[:,df.columns != ' Flow Packets/s' or df.columns != 'Flow Bytes/s']
normalized_df=(df-df.mean())/df.std()
normalized_df=normalized_df.drop(' Flow Packets/s',axis=1)
normalized_df=normalized_df.drop('Flow Bytes/s',axis=1)

In [0]:
import matplotlib.pyplot as plt
import seaborn as sn
plt.figure(figsize=(100,200))
cor = normalized_df.corr()
sn.heatmap(cor, annot=True, cmap=plt.cm.Reds)
plt.show()

In [0]:
#df=df.drop('Unnamed: 0.1',axis=1)
normalized_df.head()

Unnamed: 0  Unnamed: 0.1.1   Source Port  ...   Idle Std   Inbound     Label
0   -1.732049        0.186725      1.395596  ...  -0.162793   0.19758 -0.731047
1   -1.732046       -0.373912      0.347887  ...  -0.162793   0.19758 -0.731047
2   -1.732043        0.213485      1.196809  ...  -0.162793   0.19758 -0.731047
3   -1.732040        0.215559      0.892029  ...  -0.162793   0.19758 -0.731047
4   -1.732038       -0.757481     -0.914218  ...  -0.162793   0.19758 -0.731047

[5 rows x 37 columns]

In [0]:
normalized_df=normalized_df.drop('Unnamed: 0', axis=1)
normalized_df=normalized_df.drop('Unnamed: 0.1.1', axis=1) 

In [0]:
y=pd.DataFrame(y)

In [0]:
normalized_df.describe()

Source Port   Destination IP  ...       Inbound         Label
count  1.245798e+06     1.245798e+06  ...  1.245798e+06  1.245798e+06
mean   1.054733e-12     1.373855e-13  ... -2.792804e-12 -4.782956e-12
std    1.000000e+00     1.000000e+00  ...  1.000000e+00  1.000000e+00
min   -9.406960e-01    -7.380619e+00  ... -5.061243e+00 -1.822172e+00
25%   -9.092742e-01     1.575856e-01  ...  1.975798e-01 -7.310472e-01
50%   -5.546851e-01     1.575856e-01  ...  1.975798e-01 -1.854849e-01
75%    1.002261e+00     1.575856e-01  ...  1.975798e-01  9.056397e-01
max    1.737069e+00     2.688699e+00  ...  1.975798e-01  1.996764e+00

[8 rows x 35 columns]

In [0]:
normalized_x=normalized_df.iloc[:,normalized_df.columns != 'Label']

In [0]:
normalized_x.describe()

Source Port   Destination IP  ...      Idle Std       Inbound
count  1.245798e+06     1.245798e+06  ...  1.245798e+06  1.245798e+06
mean   1.054733e-12     1.373855e-13  ... -1.166242e-12 -2.792804e-12
std    1.000000e+00     1.000000e+00  ...  1.000000e+00  1.000000e+00
min   -9.406960e-01    -7.380619e+00  ... -1.627934e-01 -5.061243e+00
25%   -9.092742e-01     1.575856e-01  ... -1.627934e-01  1.975798e-01
50%   -5.546851e-01     1.575856e-01  ... -1.627934e-01  1.975798e-01
75%    1.002261e+00     1.575856e-01  ... -1.627934e-01  1.975798e-01
max    1.737069e+00     2.688699e+00  ...  5.903799e+01  1.975798e-01

[8 rows x 34 columns]

In [0]:
from sklearn.model_selection import train_test_split
import numpy as np
X_train, X_test, y_train, y_test = train_test_split(normalized_x, y, test_size=0.25, random_state=0)
y_train = np.array(y_train)

In [0]:
normalized_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1245798 entries, 0 to 1245797
Data columns (total 34 columns):
 Source Port                   1245798 non-null float64
 Destination IP                1245798 non-null float64
 Destination Port              1245798 non-null float64
 Protocol                      1245798 non-null float64
Total Length of Fwd Packets    1245798 non-null float64
 Fwd Packet Length Max         1245798 non-null float64
 Fwd Packet Length Min         1245798 non-null float64
 Fwd Packet Length Mean        1245798 non-null float64
Bwd Packet Length Max          1245798 non-null float64
 Bwd Packet Length Min         1245798 non-null float64
 Bwd Packet Length Mean        1245798 non-null float64
 Bwd Packet Length Std         1245798 non-null float64
 Flow IAT Mean                 1245798 non-null float64
 Flow IAT Std                  1245798 non-null float64
 Fwd IAT Mean                  1245798 non-null float64
 Fwd IAT Std                   1245798 non-null

In [0]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1245798 entries, 0 to 1245797
Data columns (total 1 columns):
Label    1245798 non-null int64
dtypes: int64(1)
memory usage: 9.5 MB


Stochastic Gradient Descent

In [0]:
#stochastic gradient descent
from  sklearn.linear_model import SGDClassifier, LinearRegression
from sklearn import metrics
lr = SGDClassifier(loss="log", penalty="l2", max_iter=200)
lr.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=200,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
y_pred = lr.predict(X_test)
print("Stochastic Gradient Descent\nAccuracy =", metrics.accuracy_score(y_test, y_pred)*100)

Stochastic Gradient Descent
Accuracy = 76.68903515813132


In [0]:
from sklearn import metrics
from sklearn.metrics import f1_score
print('Stochastic Gradient Descent')

print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                 digits=2, 
                                                                 output_dict=False))

print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

Stochastic Gradient Descent
Accuracy =  76.68903515813132
Confusion Matrix =
 [[14105    51     0     0    25    65    38    37]
 [    0 36664     2     1 13082     2    11     0]
 [    3     9 49422   363    17     7     1     0]
 [    0     1   292 47515   839     1  1626     1]
 [   24 34854     0   124 11761   116    33     6]
 [    9     0     0     4     0 49651     0     0]
 [    2     0     0 20457    13     4 29682     9]
 [   23     0     0   229    41    20   160    48]]
Recall = 0.7668903515813132
Classification Report =
               precision    recall  f1-score   support

           0       1.00      0.98      0.99     14321
           1       0.51      0.74      0.60     49762
           2       0.99      0.99      0.99     49822
           3       0.69      0.95      0.80     50275
           4       0.46      0.25      0.32     46918
           5       1.00      1.00      1.00     49664
           6       0.94      0.59      0.73     50167
           7       0.48    

In [0]:
yt = y_test.iloc[:,0]
yt=np.array(yt)

In [0]:
y_pred[3]

2

In [0]:
y_test = yt
#y_pred = y_pred[:, 0]

KNN Classifier

In [0]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=8)
model.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

In [0]:
y_pred = model.predict(X_test)
print("Accuracy =", metrics.accuracy_score(y_test, y_pred))

Accuracy = 0.8700979290415797


In [0]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('K Nearest Neighbour Classifier')

print('Accuracy = ', metrics.accuracy_score(y_test, y_pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                  digits=2, 
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

K Nearest Neighbour Classifier
Accuracy =  87.00979290415796
Confusion Matrix =
 [[14317     0     0     0     2     0     2     0]
 [    1 36944     2    12 12802     1     0     0]
 [    3     4 49750    56     6     3     0     0]
 [    0     0    54 48840    26     0  1354     1]
 [    8 24436    11    67 22379     1     6    10]
 [    6     0     0     1     1 49654     2     0]
 [    1     0     0  1200    12     1 48915    38]
 [    2     0     0    15    39     2   270   193]]
Recall = 0.8700979290415797
Classification Report =
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     14321
           1       0.60      0.74      0.66     49762
           2       1.00      1.00      1.00     49822
           3       0.97      0.97      0.97     50275
           4       0.63      0.48      0.54     46918
           5       1.00      1.00      1.00     49664
           6       0.97      0.98      0.97     50167
           7       0.80 

Naive Bayes

In [0]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
pred = model.predict(X_test)

In [0]:
from sklearn import metrics
from sklearn.metrics import f1_score

print('Naive Bayes')

print('Accuracy = ', metrics.accuracy_score(y_test, pred)*100)
print("Confusion Matrix =\n", metrics.confusion_matrix(y_test, y_pred, labels=None, 
                                              sample_weight=None))
print("Recall =", metrics.recall_score(y_test, y_pred, labels=None, 
                                             pos_label=1, average='weighted', 
                                             sample_weight=None))
print("Classification Report =\n", metrics.classification_report(y_test, y_pred, 
                                                                 labels=None, 
                                                                 target_names=None, 
                                                                 sample_weight=None, 
                                                                  digits=2, 
                                                                 output_dict=False))
print("F1 Score = ",f1_score(y_test, y_pred, average='macro'))

Naive Bayes
Accuracy =  78.31658372130357
Confusion Matrix =
 [[14317     0     0     0     2     0     2     0]
 [    1 31901     2    10 17847     1     0     0]
 [    3     3 49751    55     7     3     0     0]
 [    0     0    52 48674    30     0  1517     2]
 [    8 20635    10    55 26188     1     7    14]
 [    6     0     0     1     1 49654     2     0]
 [    1     0     0  1076    14     1 49022    53]
 [    2     0     0    15    36     2   252   214]]
Recall = 0.8660170171777172
Classification Report =
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     14321
           1       0.61      0.64      0.62     49762
           2       1.00      1.00      1.00     49822
           3       0.98      0.97      0.97     50275
           4       0.59      0.56      0.58     46918
           5       1.00      1.00      1.00     49664
           6       0.96      0.98      0.97     50167
           7       0.76      0.41      0.53